set(ITKAnisotropicSmoothing_LOADED 1)
set(ITKAnisotropicSmoothing_ENABLE_SHARED "0")
set(ITKAnisotropicSmoothing_DEPENDS "ITKCurvatureFlow;ITKImageGrid")
set(ITKAnisotropicSmoothing_PUBLIC_DEPENDS "")
set(ITKAnisotropicSmoothing_TRANSITIVE_DEPENDS "ITKCurvatureFlow;ITKImageGrid")
set(ITKAnisotropicSmoothing_PRIVATE_DEPENDS "")
set(ITKAnisotropicSmoothing_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKAnisotropicSmoothing_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKAnisotropicSmoothing_LIBRARY_DIRS "")
set(ITKAnisotropicSmoothing_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKAnisotropicSmoothing_TARGETS_FILE "")
set(ITKAnisotropicSmoothing_FACTORY_NAMES "")

