set(ITKAntiAlias_LOADED 1)
set(ITKAntiAlias_ENABLE_SHARED "0")
set(ITKAntiAlias_DEPENDS "ITKLevelSets")
set(ITKAntiAlias_PUBLIC_DEPENDS "")
set(ITKAntiAlias_TRANSITIVE_DEPENDS "ITKLevelSets")
set(ITKAntiAlias_PRIVATE_DEPENDS "")
set(ITKAntiAlias_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKLabelMap;ITKMathematicalMorphology;ITKSpatialObjects;ITKPath;ITKFastMarching;ITKIOImageBase;ITKImageFeature;ITKOptimizers")
set(ITKAntiAlias_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKAntiAlias_LIBRARY_DIRS "")
set(ITKAntiAlias_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKAntiAlias_TARGETS_FILE "")
set(ITKAntiAlias_FACTORY_NAMES "")

