set(ITKCurvatureFlow_LOADED 1)
set(ITKCurvatureFlow_ENABLE_SHARED "0")
set(ITKCurvatureFlow_DEPENDS "ITKFiniteDifference;ITKImageFilterBase")
set(ITKCurvatureFlow_PUBLIC_DEPENDS "")
set(ITKCurvatureFlow_TRANSITIVE_DEPENDS "ITKFiniteDifference;ITKImageFilterBase")
set(ITKCurvatureFlow_PRIVATE_DEPENDS "")
set(ITKCurvatureFlow_LIBRARIES "ITKCommon")
set(ITKCurvatureFlow_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKCurvatureFlow_LIBRARY_DIRS "")
set(ITKCurvatureFlow_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKCurvatureFlow_TARGETS_FILE "")
set(ITKCurvatureFlow_FACTORY_NAMES "")

