set(ITKConvolution_LOADED 1)
set(ITKConvolution_ENABLE_SHARED "1")
set(ITKConvolution_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_PUBLIC_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_TRANSITIVE_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_PRIVATE_DEPENDS "")
set(ITKConvolution_LIBRARIES "ITKConvolution")
set(ITKConvolution_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKConvolution_LIBRARY_DIRS "")
set(ITKConvolution_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKConvolution_TARGETS_FILE "")
set(ITKConvolution_FACTORY_NAMES "")

