set(ITKDeconvolution_LOADED 1)
set(ITKDeconvolution_ENABLE_SHARED "0")
set(ITKDeconvolution_DEPENDS "ITKConvolution;ITKImageSources")
set(ITKDeconvolution_PUBLIC_DEPENDS "")
set(ITKDeconvolution_TRANSITIVE_DEPENDS "ITKConvolution;ITKImageSources")
set(ITKDeconvolution_PRIVATE_DEPENDS "")
set(ITKDeconvolution_LIBRARIES "ITKConvolution;ITKCommon")
set(ITKDeconvolution_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKDeconvolution_LIBRARY_DIRS "")
set(ITKDeconvolution_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKDeconvolution_TARGETS_FILE "")
set(ITKDeconvolution_FACTORY_NAMES "")

