set(ITKDenoising_LOADED 1)
set(ITKDenoising_ENABLE_SHARED "1")
set(ITKDenoising_DEPENDS "ITKIOImageBase;ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKStatistics")
set(ITKDenoising_PUBLIC_DEPENDS "")
set(ITKDenoising_TRANSITIVE_DEPENDS "ITKIOImageBase;ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKStatistics")
set(ITKDenoising_PRIVATE_DEPENDS "")
set(ITKDenoising_LIBRARIES "ITKDenoising")
set(ITKDenoising_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKDenoising_LIBRARY_DIRS "")
set(ITKDenoising_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKDenoising_TARGETS_FILE "")
set(ITKDenoising_FACTORY_NAMES "")

