set(ITKDeformableMesh_LOADED 1)
set(ITKDeformableMesh_ENABLE_SHARED "1")
set(ITKDeformableMesh_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_PUBLIC_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_TRANSITIVE_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_PRIVATE_DEPENDS "")
set(ITKDeformableMesh_LIBRARIES "ITKDeformableMesh")
set(ITKDeformableMesh_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKDeformableMesh_LIBRARY_DIRS "")
set(ITKDeformableMesh_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKDeformableMesh_TARGETS_FILE "")
set(ITKDeformableMesh_FACTORY_NAMES "")

