set(ITKGPUAnisotropicSmoothing_LOADED 1)
set(ITKGPUAnisotropicSmoothing_ENABLE_SHARED "0")
set(ITKGPUAnisotropicSmoothing_DEPENDS "ITKAnisotropicSmoothing;ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference")
set(ITKGPUAnisotropicSmoothing_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference")
set(ITKGPUAnisotropicSmoothing_TRANSITIVE_DEPENDS "ITKAnisotropicSmoothing;ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference")
set(ITKGPUAnisotropicSmoothing_PRIVATE_DEPENDS "")
set(ITKGPUAnisotropicSmoothing_LIBRARIES "ITKGPUAnisotropicSmoothing")
set(ITKGPUAnisotropicSmoothing_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/include")
set(ITKGPUAnisotropicSmoothing_LIBRARY_DIRS "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/lib/x64/OpenCL.lib")
set(ITKGPUAnisotropicSmoothing_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUAnisotropicSmoothing_TARGETS_FILE "")
set(ITKGPUAnisotropicSmoothing_FACTORY_NAMES "")

