set(ITKGPUPDEDeformableRegistration_LOADED 1)
set(ITKGPUPDEDeformableRegistration_ENABLE_SHARED "0")
set(ITKGPUPDEDeformableRegistration_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference;ITKGPURegistrationCommon;ITKPDEDeformableRegistration")
set(ITKGPUPDEDeformableRegistration_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference")
set(ITKGPUPDEDeformableRegistration_TRANSITIVE_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference;ITKGPURegistrationCommon;ITKPDEDeformableRegistration")
set(ITKGPUPDEDeformableRegistration_PRIVATE_DEPENDS "")
set(ITKGPUPDEDeformableRegistration_LIBRARIES "ITKGPUPDEDeformableRegistration")
set(ITKGPUPDEDeformableRegistration_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/include")
set(ITKGPUPDEDeformableRegistration_LIBRARY_DIRS "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/lib/x64/OpenCL.lib")
set(ITKGPUPDEDeformableRegistration_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUPDEDeformableRegistration_TARGETS_FILE "")
set(ITKGPUPDEDeformableRegistration_FACTORY_NAMES "")

