set(ITKGPUFiniteDifference_LOADED 1)
set(ITKGPUFiniteDifference_ENABLE_SHARED "1")
set(ITKGPUFiniteDifference_DEPENDS "ITKCommon;ITKFiniteDifference;ITKGPUCommon")
set(ITKGPUFiniteDifference_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUFiniteDifference_TRANSITIVE_DEPENDS "ITKCommon;ITKFiniteDifference;ITKGPUCommon")
set(ITKGPUFiniteDifference_PRIVATE_DEPENDS "")
set(ITKGPUFiniteDifference_LIBRARIES "ITKGPUFiniteDifference")
set(ITKGPUFiniteDifference_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/include")
set(ITKGPUFiniteDifference_LIBRARY_DIRS "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/lib/x64/OpenCL.lib")
set(ITKGPUFiniteDifference_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUFiniteDifference_TARGETS_FILE "")
set(ITKGPUFiniteDifference_FACTORY_NAMES "")

