set(ITKIOStimulate_LOADED 1)
set(ITKIOStimulate_ENABLE_SHARED "1")
set(ITKIOStimulate_DEPENDS "ITKIOImageBase")
set(ITKIOStimulate_PUBLIC_DEPENDS "ITKIOImageBase")
set(ITKIOStimulate_TRANSITIVE_DEPENDS "ITKIOImageBase")
set(ITKIOStimulate_PRIVATE_DEPENDS "")
set(ITKIOStimulate_LIBRARIES "ITKIOStimulate")
set(ITKIOStimulate_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKIOStimulate_LIBRARY_DIRS "")
set(ITKIOStimulate_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKIOStimulate_TARGETS_FILE "")
set(ITKIOStimulate_FACTORY_NAMES "ImageIO::Stimulate")

