set(ITKImageSources_LOADED 1)
set(ITKImageSources_ENABLE_SHARED "0")
set(ITKImageSources_DEPENDS "ITKCommon")
set(ITKImageSources_PUBLIC_DEPENDS "")
set(ITKImageSources_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKImageSources_PRIVATE_DEPENDS "")
set(ITKImageSources_LIBRARIES "ITKCommon")
set(ITKImageSources_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageSources_LIBRARY_DIRS "")
set(ITKImageSources_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageSources_TARGETS_FILE "")
set(ITKImageSources_FACTORY_NAMES "")

