set(ITKIOTransformBase_LOADED 1)
set(ITKIOTransformBase_ENABLE_SHARED "1")
set(ITKIOTransformBase_DEPENDS "ITKCommon;ITKDisplacementField;ITKTransform;ITKTransformFactory")
set(ITKIOTransformBase_PUBLIC_DEPENDS "ITKCommon;ITKTransform;ITKTransformFactory")
set(ITKIOTransformBase_TRANSITIVE_DEPENDS "ITKCommon;ITKDisplacementField;ITKTransform;ITKTransformFactory")
set(ITKIOTransformBase_PRIVATE_DEPENDS "")
set(ITKIOTransformBase_LIBRARIES "ITKIOTransformBase")
set(ITKIOTransformBase_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKIOTransformBase_LIBRARY_DIRS "")
set(ITKIOTransformBase_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKIOTransformBase_TARGETS_FILE "")
set(ITKIOTransformBase_FACTORY_NAMES "")

