set(ITKIOTransformMatlab_LOADED 1)
set(ITKIOTransformMatlab_ENABLE_SHARED "1")
set(ITKIOTransformMatlab_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformMatlab_PUBLIC_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformMatlab_TRANSITIVE_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformMatlab_PRIVATE_DEPENDS "")
set(ITKIOTransformMatlab_LIBRARIES "ITKIOTransformMatlab")
set(ITKIOTransformMatlab_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKIOTransformMatlab_LIBRARY_DIRS "")
set(ITKIOTransformMatlab_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKIOTransformMatlab_TARGETS_FILE "")
set(ITKIOTransformMatlab_FACTORY_NAMES "TransformIO::Matlab")

