set(ITKImageFrequency_LOADED 1)
set(ITKImageFrequency_ENABLE_SHARED "0")
set(ITKImageFrequency_DEPENDS "ITKCommon")
set(ITKImageFrequency_PUBLIC_DEPENDS "ITKCommon")
set(ITKImageFrequency_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKImageFrequency_PRIVATE_DEPENDS "")
set(ITKImageFrequency_LIBRARIES "ITKCommon")
set(ITKImageFrequency_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageFrequency_LIBRARY_DIRS "")
set(ITKImageFrequency_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageFrequency_TARGETS_FILE "")
set(ITKImageFrequency_FACTORY_NAMES "")

