set(ITKIntegratedTest_LOADED 1)
set(ITKIntegratedTest_ENABLE_SHARED "0")
set(ITKIntegratedTest_DEPENDS "")
set(ITKIntegratedTest_PUBLIC_DEPENDS "")
set(ITKIntegratedTest_TRANSITIVE_DEPENDS "")
set(ITKIntegratedTest_PRIVATE_DEPENDS "")
set(ITKIntegratedTest_LIBRARIES "")
set(ITKIntegratedTest_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKIntegratedTest_LIBRARY_DIRS "")
set(ITKIntegratedTest_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKIntegratedTest_TARGETS_FILE "")
set(ITKIntegratedTest_FACTORY_NAMES "")

