set(ITKImageFeature_LOADED 1)
set(ITKImageFeature_ENABLE_SHARED "1")
set(ITKImageFeature_DEPENDS "ITKImageGradient;ITKImageSources;ITKImageStatistics;ITKMesh;ITKSmoothing;ITKSpatialObjects")
set(ITKImageFeature_PUBLIC_DEPENDS "ITKSmoothing;ITKSpatialObjects")
set(ITKImageFeature_TRANSITIVE_DEPENDS "ITKImageGradient;ITKImageSources;ITKImageStatistics;ITKMesh;ITKSmoothing;ITKSpatialObjects")
set(ITKImageFeature_PRIVATE_DEPENDS "")
set(ITKImageFeature_LIBRARIES "ITKImageFeature")
set(ITKImageFeature_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageFeature_LIBRARY_DIRS "")
set(ITKImageFeature_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageFeature_TARGETS_FILE "")
set(ITKImageFeature_FACTORY_NAMES "")

