set(ITKImageNoise_LOADED 1)
set(ITKImageNoise_ENABLE_SHARED "0")
set(ITKImageNoise_DEPENDS "ITKStatistics")
set(ITKImageNoise_PUBLIC_DEPENDS "")
set(ITKImageNoise_TRANSITIVE_DEPENDS "ITKStatistics")
set(ITKImageNoise_PRIVATE_DEPENDS "")
set(ITKImageNoise_LIBRARIES "ITKStatistics")
set(ITKImageNoise_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageNoise_LIBRARY_DIRS "")
set(ITKImageNoise_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageNoise_TARGETS_FILE "")
set(ITKImageNoise_FACTORY_NAMES "")

