set(ITKImageCompare_LOADED 1)
set(ITKImageCompare_ENABLE_SHARED "0")
set(ITKImageCompare_DEPENDS "ITKImageFilterBase;ITKImageIntensity")
set(ITKImageCompare_PUBLIC_DEPENDS "ITKImageIntensity")
set(ITKImageCompare_TRANSITIVE_DEPENDS "ITKImageFilterBase;ITKImageIntensity")
set(ITKImageCompare_PRIVATE_DEPENDS "")
set(ITKImageCompare_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageCompare_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageCompare_LIBRARY_DIRS "")
set(ITKImageCompare_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageCompare_TARGETS_FILE "")
set(ITKImageCompare_FACTORY_NAMES "")

