set(ITKImageFilterBase_LOADED 1)
set(ITKImageFilterBase_ENABLE_SHARED "0")
set(ITKImageFilterBase_DEPENDS "ITKCommon")
set(ITKImageFilterBase_PUBLIC_DEPENDS "")
set(ITKImageFilterBase_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKImageFilterBase_PRIVATE_DEPENDS "")
set(ITKImageFilterBase_LIBRARIES "ITKCommon")
set(ITKImageFilterBase_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageFilterBase_LIBRARY_DIRS "")
set(ITKImageFilterBase_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageFilterBase_TARGETS_FILE "")
set(ITKImageFilterBase_FACTORY_NAMES "")

