set(ITKImageFusion_LOADED 1)
set(ITKImageFusion_ENABLE_SHARED "0")
set(ITKImageFusion_DEPENDS "ITKBinaryMathematicalMorphology;ITKImageLabel")
set(ITKImageFusion_PUBLIC_DEPENDS "")
set(ITKImageFusion_TRANSITIVE_DEPENDS "ITKBinaryMathematicalMorphology;ITKImageLabel")
set(ITKImageFusion_PRIVATE_DEPENDS "")
set(ITKImageFusion_LIBRARIES "ITKLabelMap;ITKMathematicalMorphology;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageFusion_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageFusion_LIBRARY_DIRS "")
set(ITKImageFusion_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageFusion_TARGETS_FILE "")
set(ITKImageFusion_FACTORY_NAMES "")

