set(ITKImageAdaptors_LOADED 1)
set(ITKImageAdaptors_ENABLE_SHARED "0")
set(ITKImageAdaptors_DEPENDS "ITKCommon")
set(ITKImageAdaptors_PUBLIC_DEPENDS "")
set(ITKImageAdaptors_TRANSITIVE_DEPENDS "")
set(ITKImageAdaptors_PRIVATE_DEPENDS "ITKCommon")
set(ITKImageAdaptors_LIBRARIES "ITKCommon")
set(ITKImageAdaptors_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageAdaptors_LIBRARY_DIRS "")
set(ITKImageAdaptors_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageAdaptors_TARGETS_FILE "")
set(ITKImageAdaptors_FACTORY_NAMES "")

