set(ITKImageGrid_LOADED 1)
set(ITKImageGrid_ENABLE_SHARED "0")
set(ITKImageGrid_DEPENDS "ITKImageFunction")
set(ITKImageGrid_PUBLIC_DEPENDS "")
set(ITKImageGrid_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKImageGrid_PRIVATE_DEPENDS "")
set(ITKImageGrid_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKImageGrid_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageGrid_LIBRARY_DIRS "")
set(ITKImageGrid_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageGrid_TARGETS_FILE "")
set(ITKImageGrid_FACTORY_NAMES "")

