set(ITKImageIntensity_LOADED 1)
set(ITKImageIntensity_ENABLE_SHARED "1")
set(ITKImageIntensity_DEPENDS "ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKPath")
set(ITKImageIntensity_PUBLIC_DEPENDS "")
set(ITKImageIntensity_TRANSITIVE_DEPENDS "ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKPath")
set(ITKImageIntensity_PRIVATE_DEPENDS "")
set(ITKImageIntensity_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageIntensity_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKImageIntensity_LIBRARY_DIRS "")
set(ITKImageIntensity_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageIntensity_TARGETS_FILE "")
set(ITKImageIntensity_FACTORY_NAMES "")

