set(ITKIOTransformInsightLegacy_LOADED 1)
set(ITKIOTransformInsightLegacy_ENABLE_SHARED "1")
set(ITKIOTransformInsightLegacy_DEPENDS "ITKDoubleConversion;ITKIOTransformBase")
set(ITKIOTransformInsightLegacy_PUBLIC_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformInsightLegacy_TRANSITIVE_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformInsightLegacy_PRIVATE_DEPENDS "ITKDoubleConversion")
set(ITKIOTransformInsightLegacy_LIBRARIES "ITKIOTransformInsightLegacy")
set(ITKIOTransformInsightLegacy_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKIOTransformInsightLegacy_LIBRARY_DIRS "")
set(ITKIOTransformInsightLegacy_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKIOTransformInsightLegacy_TARGETS_FILE "")
set(ITKIOTransformInsightLegacy_FACTORY_NAMES "TransformIO::Txt")

