set(ITKKLMRegionGrowing_LOADED 1)
set(ITKKLMRegionGrowing_ENABLE_SHARED "1")
set(ITKKLMRegionGrowing_DEPENDS "ITKCommon")
set(ITKKLMRegionGrowing_PUBLIC_DEPENDS "ITKCommon")
set(ITKKLMRegionGrowing_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKKLMRegionGrowing_PRIVATE_DEPENDS "")
set(ITKKLMRegionGrowing_LIBRARIES "ITKKLMRegionGrowing")
set(ITKKLMRegionGrowing_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKKLMRegionGrowing_LIBRARY_DIRS "")
set(ITKKLMRegionGrowing_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKKLMRegionGrowing_TARGETS_FILE "")
set(ITKKLMRegionGrowing_FACTORY_NAMES "")

