set(ITKLabelVoting_LOADED 1)
set(ITKLabelVoting_ENABLE_SHARED "0")
set(ITKLabelVoting_DEPENDS "ITKThresholding")
set(ITKLabelVoting_PUBLIC_DEPENDS "ITKThresholding")
set(ITKLabelVoting_TRANSITIVE_DEPENDS "ITKThresholding")
set(ITKLabelVoting_PRIVATE_DEPENDS "")
set(ITKLabelVoting_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKLabelVoting_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKLabelVoting_LIBRARY_DIRS "")
set(ITKLabelVoting_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKLabelVoting_TARGETS_FILE "")
set(ITKLabelVoting_FACTORY_NAMES "")

