set(ITKLabelMap_LOADED 1)
set(ITKLabelMap_ENABLE_SHARED "1")
set(ITKLabelMap_DEPENDS "ITKImageLabel;ITKStatistics;ITKTransform")
set(ITKLabelMap_PUBLIC_DEPENDS "ITKImageLabel")
set(ITKLabelMap_TRANSITIVE_DEPENDS "ITKImageLabel;ITKTransform")
set(ITKLabelMap_PRIVATE_DEPENDS "ITKStatistics")
set(ITKLabelMap_LIBRARIES "ITKLabelMap")
set(ITKLabelMap_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKLabelMap_LIBRARY_DIRS "")
set(ITKLabelMap_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKLabelMap_TARGETS_FILE "")
set(ITKLabelMap_FACTORY_NAMES "")

