set(ITKLevelSets_LOADED 1)
set(ITKLevelSets_ENABLE_SHARED "0")
set(ITKLevelSets_DEPENDS "ITKAnisotropicSmoothing;ITKDistanceMap;ITKFastMarching;ITKFiniteDifference;ITKIOImageBase;ITKImageCompare;ITKImageFeature;ITKNarrowBand;ITKOptimizers;ITKSignedDistanceFunction;ITKThresholding")
set(ITKLevelSets_PUBLIC_DEPENDS "ITKAnisotropicSmoothing;ITKDistanceMap;ITKFastMarching;ITKFiniteDifference;ITKImageCompare;ITKImageFeature;ITKNarrowBand;ITKOptimizers;ITKSignedDistanceFunction;ITKThresholding")
set(ITKLevelSets_TRANSITIVE_DEPENDS "ITKAnisotropicSmoothing;ITKDistanceMap;ITKFastMarching;ITKFiniteDifference;ITKIOImageBase;ITKImageCompare;ITKImageFeature;ITKNarrowBand;ITKOptimizers;ITKSignedDistanceFunction;ITKThresholding")
set(ITKLevelSets_PRIVATE_DEPENDS "")
set(ITKLevelSets_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKLabelMap;ITKMathematicalMorphology;ITKSpatialObjects;ITKPath;ITKFastMarching;ITKIOImageBase;ITKImageFeature;ITKOptimizers")
set(ITKLevelSets_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKLevelSets_LIBRARY_DIRS "")
set(ITKLevelSets_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKLevelSets_TARGETS_FILE "")
set(ITKLevelSets_FACTORY_NAMES "")

