set(ITKNarrowBand_LOADED 1)
set(ITKNarrowBand_ENABLE_SHARED "0")
set(ITKNarrowBand_DEPENDS "ITKCurvatureFlow;ITKFiniteDifference;ITKImageIntensity")
set(ITKNarrowBand_PUBLIC_DEPENDS "ITKCurvatureFlow;ITKFiniteDifference;ITKImageIntensity")
set(ITKNarrowBand_TRANSITIVE_DEPENDS "ITKCurvatureFlow;ITKFiniteDifference;ITKImageIntensity")
set(ITKNarrowBand_PRIVATE_DEPENDS "")
set(ITKNarrowBand_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKNarrowBand_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKNarrowBand_LIBRARY_DIRS "")
set(ITKNarrowBand_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKNarrowBand_TARGETS_FILE "")
set(ITKNarrowBand_FACTORY_NAMES "")

