set(ITKQuadEdgeMesh_LOADED 1)
set(ITKQuadEdgeMesh_ENABLE_SHARED "1")
set(ITKQuadEdgeMesh_DEPENDS "ITKCommon;ITKMesh")
set(ITKQuadEdgeMesh_PUBLIC_DEPENDS "")
set(ITKQuadEdgeMesh_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKQuadEdgeMesh_PRIVATE_DEPENDS "ITKMesh")
set(ITKQuadEdgeMesh_LIBRARIES "ITKQuadEdgeMesh")
set(ITKQuadEdgeMesh_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKQuadEdgeMesh_LIBRARY_DIRS "")
set(ITKQuadEdgeMesh_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKQuadEdgeMesh_TARGETS_FILE "")
set(ITKQuadEdgeMesh_FACTORY_NAMES "")

