set(ITKRegionGrowing_LOADED 1)
set(ITKRegionGrowing_ENABLE_SHARED "1")
set(ITKRegionGrowing_DEPENDS "ITKThresholding")
set(ITKRegionGrowing_PUBLIC_DEPENDS "ITKThresholding")
set(ITKRegionGrowing_TRANSITIVE_DEPENDS "ITKThresholding")
set(ITKRegionGrowing_PRIVATE_DEPENDS "")
set(ITKRegionGrowing_LIBRARIES "ITKRegionGrowing")
set(ITKRegionGrowing_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKRegionGrowing_LIBRARY_DIRS "")
set(ITKRegionGrowing_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKRegionGrowing_TARGETS_FILE "")
set(ITKRegionGrowing_FACTORY_NAMES "")

