set(ITKSignedDistanceFunction_LOADED 1)
set(ITKSignedDistanceFunction_ENABLE_SHARED "0")
set(ITKSignedDistanceFunction_DEPENDS "ITKImageFunction")
set(ITKSignedDistanceFunction_PUBLIC_DEPENDS "ITKImageFunction")
set(ITKSignedDistanceFunction_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKSignedDistanceFunction_PRIVATE_DEPENDS "")
set(ITKSignedDistanceFunction_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKSignedDistanceFunction_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKSignedDistanceFunction_LIBRARY_DIRS "")
set(ITKSignedDistanceFunction_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKSignedDistanceFunction_TARGETS_FILE "")
set(ITKSignedDistanceFunction_FACTORY_NAMES "")

