set(ITKStatistics_LOADED 1)
set(ITKStatistics_ENABLE_SHARED "1")
set(ITKStatistics_DEPENDS "ITKCommon;ITKNetlib")
set(ITKStatistics_PUBLIC_DEPENDS "ITKCommon;ITKNetlib")
set(ITKStatistics_TRANSITIVE_DEPENDS "ITKCommon;ITKNetlib")
set(ITKStatistics_PRIVATE_DEPENDS "")
set(ITKStatistics_LIBRARIES "ITKStatistics")
set(ITKStatistics_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKStatistics_LIBRARY_DIRS "")
set(ITKStatistics_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKStatistics_TARGETS_FILE "")
set(ITKStatistics_FACTORY_NAMES "")

