set(ITKSmoothing_LOADED 1)
set(ITKSmoothing_ENABLE_SHARED "1")
set(ITKSmoothing_DEPENDS "ITKImageFunction")
set(ITKSmoothing_PUBLIC_DEPENDS "")
set(ITKSmoothing_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKSmoothing_PRIVATE_DEPENDS "")
set(ITKSmoothing_LIBRARIES "ITKSmoothing")
set(ITKSmoothing_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKSmoothing_LIBRARY_DIRS "")
set(ITKSmoothing_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKSmoothing_TARGETS_FILE "")
set(ITKSmoothing_FACTORY_NAMES "")

