set(ITKTransformFactory_LOADED 1)
set(ITKTransformFactory_ENABLE_SHARED "0")
set(ITKTransformFactory_DEPENDS "ITKCommon;ITKDisplacementField;ITKTransform")
set(ITKTransformFactory_PUBLIC_DEPENDS "ITKCommon;ITKTransform")
set(ITKTransformFactory_TRANSITIVE_DEPENDS "ITKCommon;ITKDisplacementField;ITKTransform")
set(ITKTransformFactory_PRIVATE_DEPENDS "")
set(ITKTransformFactory_LIBRARIES "ITKTransformFactory")
set(ITKTransformFactory_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKTransformFactory_LIBRARY_DIRS "")
set(ITKTransformFactory_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKTransformFactory_TARGETS_FILE "")
set(ITKTransformFactory_FACTORY_NAMES "")

