set(ITKThresholding_LOADED 1)
set(ITKThresholding_ENABLE_SHARED "0")
set(ITKThresholding_DEPENDS "ITKImageIntensity;ITKImageStatistics")
set(ITKThresholding_PUBLIC_DEPENDS "ITKImageIntensity")
set(ITKThresholding_TRANSITIVE_DEPENDS "ITKImageIntensity;ITKImageStatistics")
set(ITKThresholding_PRIVATE_DEPENDS "")
set(ITKThresholding_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKThresholding_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKThresholding_LIBRARY_DIRS "")
set(ITKThresholding_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKThresholding_TARGETS_FILE "")
set(ITKThresholding_FACTORY_NAMES "")

