set(ITKVNLInstantiation_LOADED 1)
set(ITKVNLInstantiation_ENABLE_SHARED "0")
set(ITKVNLInstantiation_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_PUBLIC_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_TRANSITIVE_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_PRIVATE_DEPENDS "")
set(ITKVNLInstantiation_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib;itkvcl")
set(ITKVNLInstantiation_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKVNLInstantiation_LIBRARY_DIRS "")
set(ITKVNLInstantiation_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKVNLInstantiation_TARGETS_FILE "")
set(ITKVNLInstantiation_FACTORY_NAMES "")

