set(ITKVideoCore_LOADED 1)
set(ITKVideoCore_ENABLE_SHARED "1")
set(ITKVideoCore_DEPENDS "ITKCommon")
set(ITKVideoCore_PUBLIC_DEPENDS "ITKCommon")
set(ITKVideoCore_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKVideoCore_PRIVATE_DEPENDS "")
set(ITKVideoCore_LIBRARIES "ITKVideoCore")
set(ITKVideoCore_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKVideoCore_LIBRARY_DIRS "")
set(ITKVideoCore_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKVideoCore_TARGETS_FILE "")
set(ITKVideoCore_FACTORY_NAMES "")

