set(ITKWatersheds_LOADED 1)
set(ITKWatersheds_ENABLE_SHARED "1")
set(ITKWatersheds_DEPENDS "ITKImageGradient;ITKImageIntensity;ITKMathematicalMorphology;ITKSmoothing;ITKThresholding")
set(ITKWatersheds_PUBLIC_DEPENDS "ITKImageGradient;ITKImageIntensity;ITKMathematicalMorphology;ITKSmoothing;ITKThresholding")
set(ITKWatersheds_TRANSITIVE_DEPENDS "ITKImageGradient;ITKImageIntensity;ITKMathematicalMorphology;ITKSmoothing;ITKThresholding")
set(ITKWatersheds_PRIVATE_DEPENDS "")
set(ITKWatersheds_LIBRARIES "ITKWatersheds")
set(ITKWatersheds_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKWatersheds_LIBRARY_DIRS "")
set(ITKWatersheds_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKWatersheds_TARGETS_FILE "")
set(ITKWatersheds_FACTORY_NAMES "")

